//// Generated by Selenium IDE
//import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//
//import java.time.Duration;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class AddCardMemberTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  private WebDriverWait wait;
//  @Before
//  public void setUp() {
//    WebDriverManager.firefoxdriver().setup();
//    driver = new FirefoxDriver();
//    driver.manage().window().maximize();
//    wait = new WebDriverWait(driver, Duration.ofSeconds(10));
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void addCardMember() {
//    driver.get("http://localhost:4000/sign_in");
//    driver.manage().window().setSize(new Dimension(1012, 1063));
//    driver.findElement(By.cssSelector("button")).click();
////    driver.findElement(By.id("add_new_board")).click();
//    wait.until(ExpectedConditions.elementToBeClickable(By.id("add_new_board"))).click();
//    driver.findElement(By.id("board_name")).sendKeys("ter");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.cssSelector(".inner")).click();
//    driver.findElement(By.id("list_name")).sendKeys("aewe");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.linkText("Add a new card...")).click();
//    {
//      By addNewCardLink = By.linkText("Add a new card...");
//      WebElement addCardElement = wait.until(ExpectedConditions.elementToBeClickable(addNewCardLink));
//      addCardElement.click();
//    }
//    driver.findElement(By.id("card_name")).sendKeys("zcsaewd");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.cssSelector(".card-content")).click();
//    driver.findElement(By.cssSelector(".button:nth-child(2) > span")).click();
//    driver.findElement(By.cssSelector(".fa-close")).click();
//    driver.findElement(By.cssSelector("li > .add-new")).click();
//    {
//      WebElement element = driver.findElement(By.cssSelector("li > .add-new"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
//    driver.findElement(By.id("crawljax_member_email")).click();
//    driver.findElement(By.id("crawljax_member_email")).sendKeys("toha@gmail.com");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.cssSelector(".card-content")).click();
//    driver.findElement(By.cssSelector(".button:nth-child(2) > span")).click();
//    {
//      WebElement element = driver.findElement(By.cssSelector(".button:nth-child(2) > span"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element).perform();
//    }
//    {
//      WebElement element = driver.findElement(By.tagName("body"));
//      Actions builder = new Actions(driver);
//      builder.moveToElement(element, 0, 0).perform();
//    }
//    driver.findElement(By.cssSelector("ul:nth-child(2) > li:nth-child(2) span:nth-child(2)")).click();
//    {
//      List<WebElement> elements = driver.findElements(By.cssSelector(".react-gravatar:nth-child(2)"));
//      assert(elements.size() > 0);
//    }
//  }
//}



import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.BoardsPage;
import org.example.CardPage;
import org.example.ListPage;
import org.example.SignInPage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;

import static org.junit.Assert.assertTrue;

public class AddCardMemberTest {
  private WebDriver driver;
  private SignInPage signInPage;
  private BoardsPage boardsPage;
  private ListPage listPage;
  private CardPage cardPage;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().maximize();
    signInPage = new SignInPage(driver);
    boardsPage = new BoardsPage(driver);
    listPage = new ListPage(driver);
    cardPage = new CardPage(driver);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void addCardMemberTest() {
    // Navigate to the sign-in page
    signInPage.navigateTo();

    // Resize window
    driver.manage().window().setSize(new Dimension(1012, 1063));

    // Login (uncomment and provide valid credentials if needed)
    // signInPage.enterEmail("valid@example.com");
    // signInPage.enterPassword("validPassword");
    signInPage.clickLoginButton();
    System.out.println("Logged in. Current URL: " + driver.getCurrentUrl());

    // Create a new board
    boardsPage.clickAddNewBoard();
    boardsPage.enterBoardName("ter");
    boardsPage.clickSubmitButton();
    System.out.println("Board created");

    // Create a new list
    boardsPage.clickInner();
    boardsPage.enterListName("aewe");
    boardsPage.clickSubmitButton();
    System.out.println("List created");

    // Create a new card
    boardsPage.clickAddNewCardLink();
    boardsPage.enterCardName("zcsaewd");
    boardsPage.clickSubmitButton();
    System.out.println("Card created");

    // Add a member to the card
    cardPage.clickCardContent();
    System.out.println("Clicked card content");
    cardPage.clickMemberButton();
    System.out.println("Clicked member button");
    cardPage.clickClosePopup();
    System.out.println("Closed popup");
    cardPage.clickAddNewMember();
    System.out.println("Clicked add new member");
    cardPage.enterMemberEmail("toha@gmail.com");
    System.out.println("Entered member email");
    cardPage.clickSubmitButton();
    System.out.println("Submitted member form");

    // Reopen member selection and select member
    cardPage.clickCardContent();
    System.out.println("Clicked card content again");
    cardPage.clickMemberButton();
    System.out.println("Clicked member button again");
    cardPage.selectMember();
    System.out.println("Selected member");

    // Take screenshot for debugging
    try {
      File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
      Files.copy(screenshot.toPath(), Paths.get("card_member_screenshot.png"));
      System.out.println("Screenshot saved as card_member_screenshot.png");
    } catch (Exception e) {
      System.out.println("Failed to save screenshot: " + e.getMessage());
    }

    // Save page source for debugging
    try {
      Files.writeString(Paths.get("card_member_source.html"), driver.getPageSource());
      System.out.println("Page source saved as card_member_source.html");
    } catch (Exception e) {
      System.out.println("Failed to save page source: " + e.getMessage());
    }

    // Verify the member avatar is present
    assertTrue("At least one member avatar should be present", cardPage.isMemberAvatarPresent());
  }
}