//// Generated by Selenium IDE
//import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//
//import java.time.Duration;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class AddCardTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    WebDriverManager.firefoxdriver().setup();
//    driver = new FirefoxDriver();
//    driver.manage().window().setSize(new Dimension(654, 751));
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void addCard() {
//    driver.get("http://localhost:4000/sign_in");
//    driver.manage().window().setSize(new Dimension(1920, 1048));
//    driver.findElement(By.cssSelector("button")).click();
//    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
//    WebElement innerElement = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".inner")));
//    innerElement.click();
//    driver.findElement(By.id("board_name")).sendKeys("First board");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.cssSelector(".inner")).click();
//    driver.findElement(By.id("list_name")).sendKeys("First listt");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.linkText("Add a new card...")).click();
//    driver.findElement(By.id("card_name")).sendKeys("new card");
//    driver.findElement(By.cssSelector("button")).click();
//    assertThat(driver.findElement(By.cssSelector(".card-content")).getText(), is("new card"));
//  }
//}




import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.BoardsPage;
import org.example.CardPage;
import org.example.ListPage;
import org.example.SignInPage;
import org.junit.*;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class AddCardTest {
  private WebDriver driver;
  private SignInPage signInPage;
  private BoardsPage boardsPage;
  private ListPage listPage;
  private CardPage cardPage;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().maximize();

    // Instantiate page objects
    signInPage = new SignInPage(driver);
    boardsPage = new BoardsPage(driver);
    listPage = new ListPage(driver);
    cardPage = new CardPage(driver);
  }

  @After
  public void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  @Test
  public void testAddCard() {
    signInPage.navigateTo();
    signInPage.clickLoginButton();

    boardsPage.selectMemberOption();
    boardsPage.enterBoardName("First board");
    boardsPage.clickSubmitButton();

    boardsPage.clickViewContainer(); // Optional if needed to open the board view again

    listPage.enterListName("First listt");
    listPage.clickSubmitButton();

    cardPage.clickAddCardLink();
    cardPage.enterCardName("new card");
    cardPage.clickSubmitButton();

    assertThat(cardPage.getCardContent(), is("new card"));
  }
}
