//// Generated by Selenium IDE
//import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//
//import java.time.Duration;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class AddListTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  private WebDriverWait wait;
//  @Before
//  public void setUp() {
//    WebDriverManager.firefoxdriver().setup();
//    driver = new FirefoxDriver();
//    driver.manage().window().maximize();
//    wait = new WebDriverWait(driver, Duration.ofSeconds(10));
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void addList() {
//    driver.get("http://localhost:4000/sign_in");
//    driver.manage().window().setSize(new Dimension(903, 1063));
//    driver.findElement(By.cssSelector("button")).click();
////    driver.findElement(By.id("add_new_board")).click();
//    By addNewBoardButton = By.id("add_new_board");
//    wait.until(ExpectedConditions.elementToBeClickable(addNewBoardButton)).click();
//
//    driver.findElement(By.id("board_name")).click();
//    driver.findElement(By.id("board_name")).sendKeys("asdczxzx");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.cssSelector(".inner")).click();
//    driver.findElement(By.id("list_name")).sendKeys("bgh");
//    driver.findElement(By.cssSelector("button")).click();
//    assertThat(driver.findElement(By.cssSelector("h4")).getText(), is("bgh"));
//  }
//}



import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.BoardsPage;
import org.example.ListPage;
import org.example.SignInPage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AddListTest {
  private WebDriver driver;
  private SignInPage signInPage;
  private BoardsPage boardsPage;
  private ListPage listPage;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().maximize();
    signInPage = new SignInPage(driver);
    boardsPage = new BoardsPage(driver);
    listPage = new ListPage(driver);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void addList() {
    // Navigate to the sign-in page
    signInPage.navigateTo();

    // Resize window
    driver.manage().window().setSize(new Dimension(903, 1063));

    // Click login button (assuming pre-authenticated session)
    signInPage.clickLoginButton();

    // Click "Add new board" button
    boardsPage.clickAddNewBoard();

    // Enter board name and submit
    boardsPage.enterBoardName("asdczxzx");
    boardsPage.clickSubmitButton();

    // Click inner element to access list creation
    boardsPage.clickInner();

    // Enter list name and submit
    boardsPage.enterListName("bgh");
    boardsPage.clickSubmitButton();

    // Verify the list title
    assertThat(listPage.getListTitle(), is("bgh"));
  }
}