//// Generated by Selenium IDE
//import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class AddmemberTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    WebDriverManager.firefoxdriver().setup();
//    driver = new FirefoxDriver();
//    driver.manage().window().setSize(new Dimension(654, 751));
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void addmember() {
//    driver.get("http://localhost:4000/sign_in");
//    driver.manage().window().setSize(new Dimension(862, 703));
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.cssSelector("#\\32-first > .inner")).click();
//    driver.findElement(By.cssSelector(".fa-plus")).click();
//    driver.findElement(By.id("crawljax_member_email")).click();
//    driver.findElement(By.id("crawljax_member_email")).sendKeys("musta@gmail.com");
//    driver.findElement(By.cssSelector("button")).click();
//  }
//}
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;
import java.util.*;

public class AddmemberTest {
  private WebDriver driver;
  private WebDriverWait wait;
  private JavascriptExecutor js;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    js = (JavascriptExecutor) driver;
    driver.manage().window().setSize(new Dimension(654, 751));
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void addmember() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(862, 703));

    // Wait for and click first button
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();

    // Wait for and click #2-first > .inner
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("#\\32-first > .inner"))).click();

    // Wait for and click .fa-plus
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".fa-plus"))).click();

    // Wait for and fill email
    WebElement emailInput = wait.until(ExpectedConditions.elementToBeClickable(By.id("crawljax_member_email")));
    emailInput.click();
    emailInput.sendKeys("musta@gmail.com");

    // Wait for and click submit button
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();
  }
}
