//// Generated by Selenium IDE
//import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//
//import java.time.Duration;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class CardCommentTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  private WebDriverWait wait;
//  @Before
//  public void setUp() {
//
//    WebDriverManager.firefoxdriver().setup();
//    driver = new FirefoxDriver();
//    driver.manage().window().setSize(new Dimension(654, 751));
//    this.wait = new WebDriverWait(driver, Duration.ofSeconds(10));
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void cardComment() {
//    driver.get("http://localhost:4000/");
//    driver.manage().window().setSize(new Dimension(1920, 1048));
//    wait.until(ExpectedConditions.elementToBeClickable(By.id("add_new_board"))).click();
//    driver.findElement(By.id("board_name")).sendKeys("one");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.cssSelector(".inner")).click();
//    driver.findElement(By.id("list_name")).sendKeys("twot");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.linkText("Add a new card...")).click();
//    driver.findElement(By.id("card_name")).sendKeys("card");
//    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.cssSelector(".card-content")).click();
//    driver.findElement(By.cssSelector("textarea")).click();
//    driver.findElement(By.cssSelector("textarea")).sendKeys("new comment");
//    driver.findElement(By.cssSelector("button")).click();
//    assertThat(driver.findElement(By.cssSelector(".text")).getText(), is("new comment"));
//  }
//}

import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.BoardsPage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class CardCommentTest {
  private WebDriver driver;
  private BoardsPage boardsPage;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(654, 751));

    // Instantiate the BoardsPage with the driver
    boardsPage = new BoardsPage(driver);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void cardComment() {
    driver.get("http://localhost:4000/");
    driver.manage().window().setSize(new Dimension(1920, 1048));

    // Use BoardsPage methods for interacting with the UI
    boardsPage.clickAddNewBoard();
    boardsPage.enterBoardName("one");
    boardsPage.clickSubmitButton();   // Clicking the button to create board

    boardsPage.clickViewContainer();  // click on .inner (view-container)

    boardsPage.enterListName("twot");
    boardsPage.clickSubmitButton();   // clicking button to add list

    boardsPage.clickAddNewCardLink();
    boardsPage.enterCardName("card");
    boardsPage.clickSubmitButton();   // click button to add card

    boardsPage.clickCardContent();
    boardsPage.enterCardComment("new comment");
    boardsPage.clickSubmitButton();   // submit the comment

    assertThat(boardsPage.getCardCommentText(), is("new comment"));
  }
}
