// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class cardTagTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private WebDriverWait wait;
  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(654, 751));
    wait = new WebDriverWait(driver, Duration.ofSeconds(10));
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void descriptioncard() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(943, 1063));
    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.id("add_new_board")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.id("add_new_board"))).click();
    driver.findElement(By.id("board_name")).sendKeys("xzcz");
//    driver.findElement(By.cssSelector("button")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();
    driver.findElement(By.cssSelector(".inner")).click();
    driver.findElement(By.id("list_name")).sendKeys("asdac");
//    driver.findElement(By.cssSelector("button")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();
    driver.findElement(By.linkText("Add a new card...")).click();
    driver.findElement(By.id("card_name")).sendKeys("fasda");
//    driver.findElement(By.cssSelector("button")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button"))).click();
    {
      WebElement element = wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector("button")));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
//    driver.findElement(By.cssSelector(".card-content")).click();
    wait.until(ExpectedConditions.elementToBeClickable(By.cssSelector(".card-content")));
    driver.findElement(By.cssSelector(".button:nth-child(3) > span")).click();
    driver.findElement(By.cssSelector(".green")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".tag:nth-child(2)"));
      assert(elements.size() > 0);
    }
  }
}
