// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CommentTimeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void commentTime() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(1151, 1063));
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.id("add_new_board")).click();
    driver.findElement(By.id("board_name")).sendKeys("rte");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".inner")).click();
    driver.findElement(By.id("list_name")).sendKeys("zzczx");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Add a new card...")).click();
    driver.findElement(By.id("card_name")).sendKeys("bnm");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".card-content")).click();
    driver.findElement(By.cssSelector("textarea")).click();
    driver.findElement(By.cssSelector("textarea")).sendKeys("qwezczv");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector("small:nth-child(3)")).getText(), is("6 hours ago"));
  }
}
