// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateBoardTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(654, 751));
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createBoard() {
    driver.get("http://localhost:4000/sign_in");
//    driver.manage().window().setSize(new Dimension(810, 703));
    driver.findElement(By.cssSelector("button")).click();
//    driver.findElement(By.id("add_new_board")).click();
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    WebElement addNewBoardButton = wait.until(ExpectedConditions.elementToBeClickable(By.id("add_new_board")));
    addNewBoardButton.click();

    driver.findElement(By.id("board_name")).sendKeys("First");
    driver.findElement(By.id("board_name")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".inner")).click();
  }
}
