//// Generated by Selenium IDE
//import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class DiffPassSignUpTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    WebDriverManager.firefoxdriver().setup();
//    driver = new FirefoxDriver();
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void diffPassSignUp() {
//    driver.get("http://localhost:4000/sign_in");
//    driver.manage().window().setSize(new Dimension(759, 1063));
//    driver.findElement(By.linkText("Create new account")).click();
//    driver.findElement(By.id("user_first_name")).click();
//    driver.findElement(By.id("user_first_name")).sendKeys("ac");
//    driver.findElement(By.id("user_last_name")).sendKeys("asdca");
//    driver.findElement(By.id("user_email")).sendKeys("abc@gmail.com");
//    driver.findElement(By.id("user_password")).sendKeys("12345");
//    driver.findElement(By.id("user_password_confirmation")).click();
//    driver.findElement(By.id("user_password_confirmation")).sendKeys("1234");
//    driver.findElement(By.cssSelector("button")).click();
//    assertThat(driver.findElement(By.cssSelector(".error")).getText(), is("Password does not match"));
//  }
//}


import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.SignInPage;
import org.example.SignUpPage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class DiffPassSignUpTest {
  private WebDriver driver;
  private SignInPage signInPage;
  private SignUpPage signUpPage;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(759, 1063));
    signInPage = new SignInPage(driver);
    signUpPage = new SignUpPage(driver);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void diffPassSignUp() {
    // Navigate to the sign-in page
    signInPage.navigateTo();

    // Click "Create new account" link
    signInPage.clickCreateNewAccountLink();

    // Fill out the sign-up form with mismatched passwords
    signUpPage.enterFirstName("ac");
    signUpPage.enterLastName("asdca");
    signUpPage.enterEmail("abc@gmail.com");
    signUpPage.enterPassword("12345");
    signUpPage.enterPasswordConfirmation("1234");

    // Submit the form
    signUpPage.clickSubmitButton();

    // Verify the error message
    assertThat(signInPage.getErrorMessage(), is("Password does not match"));
  }
}