//// Generated by Selenium IDE
//import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//
//import java.time.Duration;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class NumberNamingTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  private WebDriverWait wait;
//  @Before
//  public void setUp() {
//    WebDriverManager.firefoxdriver().setup();
//    driver = new FirefoxDriver();
//    driver.manage().window().setSize(new Dimension(654, 751));
//    wait = new WebDriverWait(driver, Duration.ofSeconds(10));
//
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void numberNaming() {
//    driver.get("http://localhost:4000/sign_in");
//    driver.manage().window().setSize(new Dimension(1920, 1048));
//    driver.findElement(By.linkText("Create new account")).click();
//    driver.findElement(By.id("user_first_name")).click();
//    driver.findElement(By.id("user_first_name")).sendKeys("123");
//    driver.findElement(By.id("user_last_name")).click();
//    driver.findElement(By.id("user_last_name")).sendKeys("23");
//    driver.findElement(By.id("user_email")).click();
//    driver.findElement(By.id("user_email")).sendKeys("abc@gmail.com");
//    driver.findElement(By.id("user_password")).sendKeys("12345");
//    driver.findElement(By.id("user_password_confirmation")).sendKeys("12345");
//    driver.findElement(By.cssSelector("button")).click();
////    assertThat(driver.findElement(By.cssSelector("span:nth-child(3)")).getText(), is("123 23"));
//    WebElement targetElement = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("span:nth-child(3)")));
//    assertThat(targetElement.getText(), is("123 23"));
//  }
//}


import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.SignInPage;
import org.example.SignUpPage;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class NumberNamingTest {
  private WebDriver driver;
  private SignInPage signInPage;
  private SignUpPage signUpPage;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(654, 751));
    signInPage = new SignInPage(driver);
    signUpPage = new SignUpPage(driver);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void numberNaming() {
    // Navigate to the sign-in page
    signInPage.navigateTo();

    // Resize window
    driver.manage().window().setSize(new Dimension(1920, 1048));

    // Click "Create new account" link
    signInPage.clickCreateNewAccountLink();

    // Fill out the sign-up form
    signUpPage.enterFirstName("123");
    signUpPage.enterLastName("23");
    signUpPage.enterEmail("abc@gmail.com");
    signUpPage.enterPassword("12345");
    signUpPage.enterPasswordConfirmation("12345");

    // Submit the form
    signUpPage.clickSubmitButton();

    // Verify the displayed name is "123 23"
    assertThat(signUpPage.getDisplayedName(), is("123 23"));
  }
}