// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class PasswordlengthTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("--headless");
        WebDriver driver = new FirefoxDriver(options);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void addlist() {
        driver.get("http://localhost:4000/sign_in");
        driver.manage().window().setSize(new Dimension(654, 751));
        driver.findElement(By.linkText("Create new account")).click();
        driver.findElement(By.id("user_first_name")).click();
        driver.findElement(By.id("user_first_name")).sendKeys("asdasc");
        driver.findElement(By.id("user_last_name")).sendKeys("sadsaca");
        driver.findElement(By.id("user_email")).sendKeys("abc@gmail.com");
        driver.findElement(By.id("user_password")).sendKeys("123");
        driver.findElement(By.id("user_password_confirmation")).sendKeys("123");
        driver.findElement(By.cssSelector("button")).click();
//    assertThat(driver.findElement(By.cssSelector(".error")).getText(), is("should be at least 5 character(s)"));
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));
        WebElement passwordError = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("password-error")));
        assertThat(passwordError.getText(), is("should be at least 5 character(s)"));
    }
}
