//// Generated by Selenium IDE
//import io.github.bonigarcia.wdm.WebDriverManager;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import static org.junit.Assert.*;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
//import org.openqa.selenium.By;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.remote.RemoteWebDriver;
//import org.openqa.selenium.remote.DesiredCapabilities;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.interactions.Actions;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//import org.openqa.selenium.JavascriptExecutor;
//import org.openqa.selenium.Alert;
//import org.openqa.selenium.Keys;
//
//import java.time.Duration;
//import java.util.*;
//import java.net.MalformedURLException;
//import java.net.URL;
//public class SignupTest {
//  private WebDriver driver;
//  private Map<String, Object> vars;
//  JavascriptExecutor js;
//  @Before
//  public void setUp() {
//    WebDriverManager.firefoxdriver().setup();
//    driver = new FirefoxDriver();
//    driver.manage().window().setSize(new Dimension(654, 751));
//  }
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
//  @Test
//  public void signup() {
//    driver.get("http://localhost:4000/sign_in");
//    driver.manage().window().setSize(new Dimension(1070, 622));
//    driver.findElement(By.linkText("Create new account")).click();
//    driver.findElement(By.id("user_first_name")).click();
//    driver.findElement(By.id("user_first_name")).sendKeys("mustaa");
//    driver.findElement(By.id("user_last_name")).sendKeys("kim");
//    driver.findElement(By.id("user_email")).sendKeys("mustaa@gmail.com");
//    driver.findElement(By.id("user_password")).sendKeys("12345");
//    driver.findElement(By.id("user_password_confirmation")).sendKeys("12345");
//    driver.findElement(By.cssSelector("button")).click();
//    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
//    WebElement nameElement = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("span:nth-child(3)")));
//
//    assertThat(nameElement.getText(), is("mustaa kim"));
//  }
//}

import io.github.bonigarcia.wdm.WebDriverManager;
import org.example.SignInPage;
import org.example.SignUpPage;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;

public class SignupTest {
  private WebDriver driver;
  private SignInPage signInPage;
  private SignUpPage signUpPage;

  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(654, 751));
    signInPage = new SignInPage(driver);
    signUpPage = new SignUpPage(driver);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void signup() {
    signInPage.navigateTo();
    driver.manage().window().setSize(new Dimension(1070, 622));
    signInPage.clickCreateNewAccountLink();
    signUpPage.enterFirstName("mustaaa");
    signUpPage.enterLastName("kim");
    signUpPage.enterEmail("mustaaa@gmail.com");
    signUpPage.enterPassword("12345");
    signUpPage.enterPasswordConfirmation("12345");
    signUpPage.clickSubmitButton();
    assertThat(signUpPage.getDisplayedName(), is("mustaaa kim"));
  }
}