// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SmallLengthPaswordTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    driver.manage().window().maximize();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void smallLengthPasword() {
    driver.get("http://localhost:4000/sign_in");
    driver.manage().window().setSize(new Dimension(1012, 1063));
    driver.findElement(By.linkText("Create new account")).click();
    driver.findElement(By.id("user_first_name")).click();
    driver.findElement(By.id("user_first_name")).sendKeys("qwe");
    driver.findElement(By.id("user_last_name")).sendKeys("qwedd");
    driver.findElement(By.id("user_email")).click();
    driver.findElement(By.id("user_email")).sendKeys("m@gmail.com");
    driver.findElement(By.id("user_password")).sendKeys("1234");
    driver.findElement(By.id("user_password_confirmation")).click();
    driver.findElement(By.id("user_password_confirmation")).sendKeys("1234");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector(".error")).getText(), is("should be at least 5 character(s)"));
  }
}
